version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
#    expose:
#      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=micro
    restart: unless-stopped

  doo-doo-backend:
    image: doo-doo-backend:latest
    container_name: doo-doo-backend
#    expose:
#      - 8080
    ports:
      - "9533:9533"
#    restart: unless-stopped
    depends_on:
      - postgres