version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=micro
    restart: unless-stopped

  doo-doo-backend:
    image: doo-doo-backend:latest
    container_name: doo-doo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9533:9533"
    depends_on:
      - postgres